image: node:latest

variables:
  # For postgres
  POSTGRES_DB: placeholder
  POSTGRES_USER: pragun
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST_AUTH_METHOD: trust

services:
  - postgres:latest
  - redis:latest

stages:
  - test

tests:
  stage: test

  before_script:
    - apt update
    - apt install -y curl tar zstd wget
    - curl -L --output vndb.tar.zst https://dl.vndb.org/dump/vndb-db-latest.tar.zst
    - tar -I zstd -xvf vndb.tar.zst
    - ls
    - apt install -y postgresql-client
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - psql --version
    - psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "SELECT VERSION();"
    - psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE DATABASE vndb;"
    - psql -h postgres -U $POSTGRES_USER -d $POSTGRES_DB -c "CREATE DATABASE vndb_backup"
    - psql -h postgres -U $POSTGRES_USER vndb < import.sql
    - psql -h postgres -U $POSTGRES_USER vndb_backup < import.sql
    # NOW SET SERVER ENV VARIABLES
    - export PGHOST=postgres
    - export PGUSER=$POSTGRES_USER
    - export PGPASSWORD=$POSTGRES_PASSWORD
    - export PGDATABASE=vndb
    - export PGBACKUPDATABASE=vndb_backup
    - export PGPORT=5432
    - export REDISHOST=redis
    - export REDISPORT=6379

  script:
    - npm install
  #   - npm run test
